'''
PROBLEM 2: 
Each new term in the Fibonacci sequence is generated by adding the previous two 
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.

ANSWER : 4613732
'''

def nextFibonacci(n1, n2) :
	return n1 + n2

def main():
	n1 = 1
	n2 = 2
	s = n2
	while True:
		n = nextFibonacci(n1, n2)
		if n % 2 == 0 :
			s += n
		if n > 4000000 : 
			break
		n1 = n2 
		n2 = n
   	print "Sum of even Fibonacci numbers less than four million is %d" % s 

if __name__ == "__main__":
    main()