#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
PROBLEM 44: 
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. 
The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their 
difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their 
sum and difference are pentagonal and D = |Pk − Pj| is minimised; 
what is the value of D?

ANSWER : 5482660
'''

def isPentagonal(number) :
	penTest = ((1.0 + 24.0 * float(number)) ** 0.5 + 1.0) / 6.0
	return penTest == int(penTest)

def main():
	not_found = True
	min_diff = 0
	i = 2
	while not_found :
		n = i * (3 * i - 1) / 2
		for j in range(1, i) : 
			m = j * (3 * j - 1) / 2
			if isPentagonal(n - m) and isPentagonal(m + n) : 
				min_diff = n - m
				not_found = False
				break
		i += 1
	print "Minimum value for D is %d" % min_diff

if __name__ == "__main__":
    main()