#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
PROBLEM 45: 
Triangle, pentagonal, and hexagonal numbers are generated by the 
following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

ANSWER : 1533776805
'''

def gen_triangle(n) :
	return n * (n + 1.0) / 2.0 

def is_pentagonal(p) :
	n = 1.0 / 6.0 * (1.0 + (24.0 * p + 1.0) ** 0.5)
	return n == int(n)

def is_hexagonal(h) : 
	n = 1.0 / 4.0 * (1.0 + (8.0 * h + 1.0) ** 0.5)
	return n == int(n)

def main():
	index = 286
	while True : 
		t = float(gen_triangle(index))
		if is_pentagonal(t) and is_hexagonal(t) :
			print "The next triangle number is %d" % int(t)
			break
		index += 1

if __name__ == "__main__":
    main()